# Generated by Django 4.2.30 on 2026-04-28 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the rubric', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of what this rubric evaluates')),
                ('assignment_type', models.CharField(blank=True, help_text="Type of assignment this rubric is for (e.g., 'essay', 'research paper')", max_length=100)),
                ('max_score', models.IntegerField(default=100, help_text='Maximum possible score for this rubric')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rubric is active for use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Rubrics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RubricCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the category (e.g., 'Argument', 'Evidence')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of what this category evaluates')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Weight of this category in the overall rubric (0.00-1.00)', max_digits=5)),
                ('order', models.IntegerField(default=0, help_text='Display order for this category')),
                ('rubric', models.ForeignKey(help_text='The rubric this category belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='feedback_system.rubric')),
            ],
            options={
                'verbose_name_plural': 'Rubric Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the criterion (e.g., 'Thesis clarity')", max_length=200)),
                ('description', models.TextField(help_text='Detailed description of what this criterion evaluates')),
                ('criterion_type', models.CharField(choices=[('argument', 'Argument'), ('evidence', 'Evidence'), ('grammar', 'Grammar'), ('structure', 'Structure'), ('style', 'Style'), ('content', 'Content'), ('analysis', 'Analysis'), ('other', 'Other')], default='other', help_text='Type of criterion for categorization', max_length=20)),
                ('max_points', models.IntegerField(default=10, help_text='Maximum points for this criterion')),
                ('order', models.IntegerField(default=0, help_text='Display order for this criterion')),
                ('category', models.ForeignKey(help_text='The category this criterion belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='feedback_system.rubriccategory')),
            ],
            options={
                'verbose_name_plural': 'Rubric Criteria',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RubricLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('satisfactory', 'Satisfactory'), ('fair', 'Fair'), ('poor', 'Poor'), ('needs_improvement', 'Needs Improvement')], help_text='Name of the performance level', max_length=50)),
                ('score_range_min', models.IntegerField(help_text='Minimum score for this level')),
                ('score_range_max', models.IntegerField(help_text='Maximum score for this level')),
                ('description', models.TextField(help_text='Description of what constitutes this level of performance')),
                ('feedback_template', models.TextField(blank=True, help_text='Template for feedback at this level (use {criteria} as placeholder)')),
                ('order', models.IntegerField(default=0, help_text='Display order for this level')),
                ('criterion', models.ForeignKey(help_text='The criterion this level belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='feedback_system.rubriccriterion')),
            ],
            options={
                'verbose_name_plural': 'Rubric Levels',
                'ordering': ['-score_range_max', 'order'],
            },
        ),
    ]
